service: frontend
plugins:
  - serverless-apigw-binary
  - serverless-offline
  - serverless-domain-manager
  - serverless-certificate-creator
provider:
  name: aws
  profile: georgi-sls
  region: eu-central-1
  runtime: nodejs12.x
  memorySize: 192
  timeout: 10
package:
  exclude:
    - ./**
  include:
    - "node_modules/aws-serverless-express/**"
    - "node_modules/binary-case/**"
    - "node_modules/type-is/**"
    - "node_modules/media-typer/**"
    - "node_modules/mime-types/**"
    - "node_modules/mime-db/**"
    - "dist/**"
    - "lambda.js"

custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: sls.georgi.io
    staging: staging.sls.georgi.io
  #    dev: dev-sg.sls.georgi.io
  #  certificates:
  #    prod: arn:aws:acm:eu-central-1:654721976277:certificate/a28cc2a8-4ee1-417c-b3dc-3e5fa42ee99f
  #    staging: arn:aws:acm:eu-central-1:654721976277:certificate/b355f92a-b801-437c-99cd-5c23e48251da
  #    dev: arn:aws:acm:eu-central-1:654721976277:certificate/8c32704a-b2b2-43c5-82d5-2dc51c93ea8f
  apigwBinary:
    types:
      - "*/*"
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    stage: "${self:custom.stage}"
    certificateName: ${self:custom.customDomain.domainName}
    basePath: ''
    createRoute53Record: true
    region: eu-central-1
  #    certificateArn: ${self:custom.certificates.${self:custom.stage}}
  customCertificate:
    certificateName: ${self:custom.customDomain.domainName}
    hostedZoneNames: 'sls.georgi.io.'
    enabled: true
    region: us-east-1
    rewriteRecords: false

functions:
  api:
    handler: lambda.handler
    events:
      - http: GET {proxy+}
      - http: GET /

#resources:
#  outputs:
#    ApiGatewayRestApiId:
#      value:
#        ref: ApiGatewayRestApi
#      export:
#        name: ${self:custom.stage}-ExtApiGatewayRestApiId
#    ApiGatewayRestApiRootResourceId:
#      value:
#        Fn::GetAtt:
#          - ApiGatewayRestApi
#          - RootResourceId
#      export:
#        name: ${self:custom.stage}-ExtApiGatewayRestApiRootResourceId
